### ISSUE TITLE
paredit overrides backspace even for Sublime (app-level) use

### ISSUE THREAD

**Issue by ghost** [odyssomay/paredit#1]
After installing, I lose the ability to use the backspace key when using the Command Palette (COMMAND+SHIFT+P).

Can you make sure that the keybinding overrides only in the correct buffer / view / context? (I'm not sure exactly how to frame the question.)

**Comment by odyssomay** [comment]
Does it stop working completely?

I think I can detect in the keybind if the command palette is open, but it should honestly work as is.

**Comment by bluemont** [comment]
Yes, backspace stops working completely. I'm using the latest Sublime Text 3.

I would recommend against testing if the command palette is open. I don't think it will work; I think you'll have a hard time covering all the special cases. (There are many other places where a user types in the application.) If you somehow succeed, it will likely be a brittle solution. I'd guess that a better way would be to test that the focus is a buffer that with paredit activated.

Speaking of, what are some ways that plugins enable themselves for a particular context? (I've seen configuration files as well as menu options.) What do you think is the best way for this plugin to use?

**Comment by odyssomay** [comment]
Does backspace work in a regular file?
You could open the console to check for any errors.

I'm not sure about the enabling part. I think a global menu option is probably desirable, but anything more complicated than that seems overkill to me.
