### ISSUE TITLE
Unable to save paredit.sublime-settings

### ISSUE THREAD

**Issue by xpe** [odyssomay/paredit#12]
Is this my fault? Or is this a permissions issue stemming from the Git repository?

> Unable to save ~/Library/Application Support/Sublime Text 3/Packages/paredit/paredit.sublime-settings
> Error: unable to create tmp file in /Users/david/Library/Application Support/Sublime Text 3/Packages/paredit

**Comment by odyssomay** [comment]
This is a sublime text 3 issue.

**Comment by xpe** [comment]
I don't understand. A known bug they are working on? Is there a workaround?

**Comment by odyssomay** [comment]
Sorry for being so short. It's not a bug, it's a side effect of the way st3 deals with installed packages. The difference is that st2 unpacks each package and moves the result into _Packages_ inside the data directory, while st3 simply uses the plugin as-is where it is. This means that the directory _Packages/paredit_ and the file _paredit.sublime-settings_ does not exist. The odd part is that the file still seems to open somehow, but I think that's what happening.

**Comment by odyssomay** [comment]
This commit is a workaround of sorts. I think it should work, but it doesn't (in other words it might be an st issue). To change the settings (or the key bindings), you have to:
1. Open the file (from the usual menu).
2. Save it.
3. Close the file.
4. Open it again (from the menu).

After that it should be editable and changing it should reload the settings automatically as usual.

**Comment by adammcarth** [comment]
Settings still fail to save. Using Sublime Text 3 and Ubuntu 13.04.

Throws this error on when I try to save my user settings config file for the first time:

```
Unable to save ~/.config/sublime-text-3/Packages/User/Preferences.sublime-settings
Error: unable to create tmp file in /home/xavier/.config/sublime-text-3/Packages/User
```

I tried making `~/.config/sublime-text-3` public, but it still didn't work.

**Comment by orangeblock** [comment]
Workaround works on Windows 7! Same issue with the keymap, same fix. There is a paredit folder in Packages but no files are saved in it. After the workaround all seems to be working, thanks!

**Comment by jarhart** [comment]
The problem here is a misunderstanding of how Sublime Text does package settings. The settings file in the package represents the "Default" settings. "User" settings should go in a file with the same name in "Packages/User". This is not new to Sublime Text 3. In ST2 if you save the changes to the settings file in the package they will get overwritten when the package is updated.

**Comment by dannymichel** [comment]
Is there no fix for this?

**Comment by jarhart** [comment]
Nothing was ever actually broken. The "fix" was to add a menu entry for your _User_ settings for Paredit. You can save changes to your _User_ settings file and they won't get overwritten when the package gets updated. Use `Preferences > Package Settings > Paredit > Settings - User` to open/create your _User_ settings file. To see what the _Default_ settings are, which you can override in your _User_ settings file, use `Preferences > Package Settings > Paredit > Settings - Default`.

**Comment by dannymichel** [comment]
Sorry about that. Hacky, but my fix was chown and chmoding my whole home folder.

**Comment by xpe** [comment]
Ok, I've tried this again. Things work. Hooray!

**Comment by lessallan** [comment]
May I humbly suggest a new error message...

Something like ..."The default settings are meant to be a reference, copy and paste the section you wish to modify into the user settings and make your modifications. You cannot edit default settings."

**Comment by xpe** [comment]
@lessallan I think the error message you are seeing may be from Sublime itself, not this plugin.

**Comment by napster-uk** [comment]
Hi,

had same issue, i think u used sudo -s to clone the repository, you need to re-clone the repository with your user name after that you can easily save the file,

Thanks

Sofiane
