### ISSUE TITLE
"No description provided" in package control

### ISSUE THREAD

**Issue by favila** [odyssomay/paredit#15]
When listing or manipulating paredit in package control, it displays "No description provided". The fix is to add a github description for the repository. I suggest something like "A paredit mode for lisps in Sublime Text". (This will probably also help your googeability.)

You should also consider [submitting this package](http://wbond.net/sublime_packages/package_control/package_developers), because it is worlds better than the one on there currently (which has been abandoned).

Love your plugin! It's a complete game-changer for lisps on sublime.

**Comment by odyssomay** [comment]
Thanks, I'll use what you suggested if you don't mind.

**Comment by odyssomay** [comment]
I don't know what you mean about submitting. This is the current package called _paredit_ in package control, have I missed something?

**Comment by favila** [comment]
Don't mind at all.

Never mind about submitting--I added your github as a package repository probably before package control picked it up, and I just assumed that nothing had changed. I see that you have already submitted it and that the other paredit I was talking about is gone now.

**Comment by odyssomay** [comment]
I see. Thanks for the contribution! :+1:
