### ISSUE TITLE
Four vital commands are absent

### ISSUE THREAD

**Issue by sdegutis** [odyssomay/paredit#16]
- `paredit-backward-up`
- `paredit-backward-down`
- `paredit-forward-up`
- `paredit-forward-down`

These are essential to paredit. Please add them?

I've tried switching to ST2 about three times in the past month (including today), but each time, I just couldn't use it because of these missing commands, and had to go back to emacs (including today). You would be a hero to many people if you added these!

**Comment by odyssomay** [comment]
Sure! Unfortunately these commands are not documented - as far as I can see - in the cheatsheet or the reference. If you could give a short explanation on how they work, that would be great. :)

**Comment by sdegutis** [comment]
Sure. Here:

#### paredit-backward-up

Go outside of the current s-exp, on the left side.

``` clojure
(foo (| bar baz))
(foo | (bar baz))
```

#### paredit-forward-down

Go down into the very-next child s-exp.

``` clojure
(foo | (bar baz))
(foo (| bar baz))
```

#### paredit-backward-down

Go down into the very-previous child s-exp.

``` clojure
(foo (bar baz) |)
(foo (bar baz |))
```

#### paredit-forward-up

Go outside of the current s-exp, on the right side.

``` clojure
(foo (bar baz |))
(foo (bar baz) |)
```

By the way, they're in the list at http://mumble.net/~campbell/emacs/paredit.html which is more comprehensive than the cheat-sheet.

**Comment by sdegutis** [comment]
Speaking of which, `paredit-raise-sexp` can probably be done by cutting the s-exp to the right of the cursor first, doing `paredit-backward-up`, deleting the s-exp to the right, and pasting that first s-exp.

**Comment by odyssomay** [comment]
This has been neglected for far too long. :(

I just implemented these commands, but I'm unsure if they do what you want (one of the reasons I didn't implement this sooner). If you still have sublime text and paredit around, it would be nice if you could test them and say what you think.

**Comment by sdegutis** [comment]
@odyssomay Coincidence that you just mentioned this, I just open sourced [Leviathan](https://github.com/sdegutis/Leviathan) today, which implements these commands too. For reference the source for the 4 functions is [here](https://github.com/sdegutis/Leviathan/blob/master/Leviathan/LVTextView.m#L536-L554) and [here](https://github.com/sdegutis/Leviathan/blob/master/Leviathan/LVTextView.m#L597-L621).

**Comment by sdegutis** [comment]
No longer a relevant request, sorry for the noise.
