### ISSUE TITLE
Can't fix unbalanced braces

### ISSUE THREAD

**Issue by taoeffect** [odyssomay/paredit#18]
``` clojure
(timbre/set-config!
 [:appenders :my-appender]
 {:doc       "Hello-world appender"
  :min-level :debug
  :enabled?  true
  :async?    false
  :limit-per-msecs nil ; No rate limit
  :fn (fn [{:keys [ap-config level prefix throwable message] :as args}]
        (println "args: " args)
        (println-str "args again: " args)
        (println prefix "Hello world!" message))|)
```

The opening brace in front of :doc is not balanced. The pipe is positioned where it should be inserted (near the very end).

For the life of me I can't figure out how to insert that damned brace while paredit is running. This shouldn't be possible. Paredit should make my life easier, not more difficult. Not sure if this is a dup of #6.

**Comment by odyssomay** [comment]
Sorry, I should have documented this already.

The current way is to insert two new brackets with _{_, then to delete the bracket you don't need with _shift+backspace_. I'm not sure this is the best solution, but I think it works fairly well. I might add shortcuts that always inserts a single bracket, but I'm not sure that's a good idea. Mostly because beginners will quickly turn to using those shortcuts instead since it's way easier than doing it the paredit way when you're not used to it (I have personally done this a lot).

**Comment by taoeffect** [comment]
I think that we can at least both agree that your solution for fixing this problem is ... counter-intuitive at best, and that's putting it delicately.

**Comment by taoeffect** [comment]
Ideally, placing the caret where it is in the code above and hitting } should close the brace. Paredit should figure out that a brace needs to be matched there. Sublime (or one of the plugins I'm using) notices and puts a ? mark in the gutter next to the line with the open brace, so maybe you could piggieback on whatever behavior does that.

**Comment by odyssomay** [comment]
Oh right, I totally forgot about that. I didn't want to do that since I thought it would have to search the whole file to see if a { is unmatched every time. I think it might be possible without doing that though. I'll think about it.

**Comment by odyssomay** [comment]
I don't see a _?_ in the gutter, my guess would be that you have https://github.com/facelessuser/BracketHighlighter installed.

**Comment by taoeffect** [comment]
Yeah, I do have that installed. Just ran into this again, except with parens this time:

![screen shot 2013-07-28 at 5 57 49 pm](https://f.cloud.github.com/assets/138706/868909/d092a8c4-f7d0-11e2-88eb-62ce7d102f09.png)

**Comment by odyssomay** [comment]
I just realized this was really easy to do. I feel silly now. :D

Thanks for opening the issue and telling me the right way to do it! :+1:

**Comment by taoeffect** [comment]
Awesome! Thanks for fixing this! :smiley:

Can you update the version settings for the Sublime package manager? I'd love to test it out! :)

**Comment by odyssomay** [comment]
It should be updated automatically. Either use _Package Control: Upgrade Package_ in the command palette or restart sublime, that should do it.

**Comment by taoeffect** [comment]
Hmm, I did the Upgrade Package command, and it gave me a list of packages that could be updated. paredit wasn't one of them. I tried restarting Sublime also but that didn't work...

**Comment by odyssomay** [comment]
That's really odd. Did you install paredit manually?

**Comment by taoeffect** [comment]
Nope, through the package manager. Just removed it (using the package manager) and reinstalled it. The version listed for installing it was the same as it was listed when I removed it:

![screen shot 2013-07-28 at 6 27 05 pm](https://f.cloud.github.com/assets/138706/868940/1de97d24-f7d5-11e2-8f6f-c87f9a62f846.png)

**Comment by odyssomay** [comment]
I see. The reason is probably because Package Control only updates every 30 minutes, if I'm not mistaken. I thought upgrading it manually would circumvent that, but I guess not...

Even so, it should fetch it from the repository, so you can test if the patch made it into your version.

EDIT: When you re-installed it that is.

**Comment by taoeffect** [comment]
Ah I see. Woo hoo!! It works! Thanks for fixing this so quickly! :-D

**Comment by odyssomay** [comment]
No problem, thanks for opening the issue. :)

Don't hesitate to open more if you find something else!
