### ISSUE TITLE
Option for disabling autoescaping of doublequote in strings

### ISSUE THREAD

**Issue by chipotle** [odyssomay/paredit#22]
When I'm entering quoted strings in all other languages in SublimeText, typing the first " mark produces two quote marks, with the cursor between them. I can type the string out and type another " mark, and the cursor will advance past the closing quote. Paredit, though, overrides this behavior, so when I try to close the string, I instead get an escaped quote mark in the string and the cursor is still in the string positioned before the closing quote mark.

I'm presuming this is working as intended, but I find I'm a _lot_ more likely to be typing that second " mark to close a string than I am to be trying to put a quote mark _in_ the string. I really like Paredit, but I'd really like ST's default behavior back. Is there an option to do this, and if not would you consider one?

**Comment by odyssomay** [comment]
There we go. This should really have been the default. Please reopen if it still doesn't work.

Thanks for reporting this!
