### ISSUE TITLE
CRTL-K hotkey conflicts with sublime modifier on Windows/Linux

### ISSUE THREAD

**Issue by fbehrens** [odyssomay/paredit#23]
iE toggling the sidebar is then not possible

**Comment by odyssomay** [comment]
I want the key bindings for this plugin to be as close to the [original paredit](http://www.emacswiki.org/emacs/ParEdit) as possible. I don't think toggling the sidebar is an important enough key binding to warrant a change to the `ctrl+k` binding in this plugin. It's easy enough to change it in the user settings.

**Comment by fbehrens** [comment]
This is very OK with me. Going to learn paredit the hotkeys make no sense to me, so I remapped them all to something which makes some sense to me. iE the six movement commands outleft-left-inleft ... are on 6 adjacent keys.

just to mention. ctrl-k acts as a modifier in sublime. I am using Origami-package which map keys beginning with ctrl-k.
