### ISSUE TITLE
CMD-S (save) is disabled

### ISSUE THREAD

**Issue by trevor** [odyssomay/paredit#3]
When installed CMD-S is disabled on OSX

**Comment by odyssomay** [comment]
Thanks for reporting! :+1: 

Comment out this code as a quickfix:

```
,{
"keys": ["super+s"],
"command": "paredit_splice_sexp"
 }
```

In _Default (OSX).sublime-keymap_.

**Comment by odyssomay** [comment]
This issue is "replaced" by #14. Interfering shortcuts will use _alt_ instead of _cmd_, and documented in the cheatsheet.
