### ISSUE TITLE
Barfage should work "one step at a time"

### ISSUE THREAD

**Issue by xpe** [odyssomay/paredit#5]
```
(defn f1 [coll f x] (conj (map f coll x)))
```

Put the point between the "m" and "a" in map. Press `ctrl+shift+]` (`paredit_forward_barf_sexp`). The expected behavior -- e.g. like emacs paredit -- is this:

```
(defn f1 [coll f x] (conj (map f coll) x))
```

If you press the key again:

```
(defn f1 [coll f x] (conj (map f) coll x))
```

And again:

```
(defn f1 [coll f x] (conj (map) f coll x))
```

**Comment by odyssomay** [comment]
Should work now. Reopen if not.
